services:
  knot:
    build:
      context: .
      args:
        UID: 1000
        GID: 1000
    environment:
      KNOT_SERVER_HOSTNAME: ${KNOT_SERVER_HOSTNAME}
      KNOT_SERVER_OWNER: ${KNOT_SERVER_OWNER}
      KNOT_SERVER_DB_PATH: /app/knotserver.db
      KNOT_REPO_SCAN_PATH: /home/git/repositories
      KNOT_SERVER_INTERNAL_LISTEN_ADDR: 0.0.0.0:5555
    volumes:
      - ./keys:/etc/ssh/keys
      - ./repositories:/home/git/repositories
      - ./server:/app
    ports:
      - "2222:22"
    restart: always
