services:
  knot:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      KNOT_SERVER_HOSTNAME: ${KNOT_SERVER_HOSTNAME}
      KNOT_SERVER_SECRET: ${KNOT_SERVER_SECRET}
      KNOT_SERVER_DB_PATH: "/app/knotserver.db"
      KNOT_REPO_SCAN_PATH: "/home/git/repositories"
    volumes:
      - "./keys:/etc/ssh/keys"
      - "./repositories:/home/git/repositories"
      - "./server:/app"
    ports:
      - "2222:22"
  frontend:
    image: caddy:2-alpine
    command: >
      caddy
      reverse-proxy
      --from ${KNOT_SERVER_HOSTNAME}
      --to knot:5555
    depends_on:
      - knot
    ports:
      - "443:443"
      - "443:443/udp"
    volumes:
      - caddy_data:/data
    restart: always
volumes:
  caddy_data:
